# Algoritmo de Gauss para escalonamento de matrizes

Esse projeto serve como treinamento de python para a disciplina de ALC

In [4]:
import numpy as np

Essa função itera atravez das colunas da matriz 

In [5]:
def calcMatriz(mArray):
    pivoX=0
    pivoY=0
    count=0
    for coluna in mArray.T:
        if np.all(coluna, 0):
            for i in range (pivoX,mArray.shape[1]-1):
                mArray = np.insert(mArray, i+1, calcCell(mArray, pivoX, pivoY, i),0)
                mArray = np.delete(mArray, i+2,0)
            pivoX+=1
        pivoY+=1
    return mArray

In [ ]:
Essa função faz o calculo para zerar o elemento abaixo do pivo

In [6]:
def calcCell(mArray, pivoX, pivoY, i):
    if mArray[i+1,pivoY] == 0:
        return mArray[i+1:]
    resposta=[]
    if mArray[pivoX, pivoY] >=0:
        try:
            resposta.append(mArray[i+1,:]-((mArray[i+1,pivoY]/mArray[pivoX,pivoY])*mArray[pivoX,:]))
        except:
            resposta.append(mArray[i+1,:]-mArray[pivoX,:])
    else:
        try:
            resposta.append(mArray[pivoX+1,:]+((mArray[pivoX+1,pivoY]/mArray[pivoX,pivoY])*mArray[pivoX,:]))
        except:
            resposta.append(mArray[pivoX+1,:]+mArray[pivoX,:])
    return resposta

In [ ]:
Essa função recebe a matriz através do input do usuario

In [7]:
def userMatrixInput():
    while (True):
        listMatrix=[]
        listLinha=[]
        print("Digite o tamanho da matriz")
        n=int(input())
        for linha in range(0, n):
            for coluna in range(0, n):
                print(f"\nDigite o elemento presente na linha {linha} coluna {coluna}: ")
                listLinha.append(int(input()))
            listMatrix.append(listLinha)
            listLinha=[]
        matrix=np.array(listMatrix)
        print("\nMatriz digitada\n")
        print(matrix)
        print("Essa é sua matriz?(s/n)")
        validade=input()
        if validade == 's':
            break
    return matrix

In [8]:
matrizEscalonada = calcMatriz(userMatrixInput())
print("A versão escalonada da sua matriz é: ")
print(matrizEscalonada)

Digite o tamanho da matriz
3

Digite o elemento presente na linha 0 coluna 0: 
3

Digite o elemento presente na linha 0 coluna 1: 
1

Digite o elemento presente na linha 0 coluna 2: 
1

Digite o elemento presente na linha 1 coluna 0: 
1

Digite o elemento presente na linha 1 coluna 1: 
1

Digite o elemento presente na linha 1 coluna 2: 
2

Digite o elemento presente na linha 2 coluna 0: 
3

Digite o elemento presente na linha 2 coluna 1: 
1

Digite o elemento presente na linha 2 coluna 2: 
3

Matriz digitada

[[3 1 1]
 [1 1 2]
 [3 1 3]]
Essa é sua matriz?(s/n)
n
Digite o tamanho da matriz
3

Digite o elemento presente na linha 0 coluna 0: 
1

Digite o elemento presente na linha 0 coluna 1: 
1

Digite o elemento presente na linha 0 coluna 2: 
1

Digite o elemento presente na linha 1 coluna 0: 
1

Digite o elemento presente na linha 1 coluna 1: 
2

Digite o elemento presente na linha 1 coluna 2: 
3

Digite o elemento presente na linha 2 coluna 0: 
1

Digite o elemento presente na linha 2