In [1]:
#import numpy 
import numpy as np

In [5]:
'''
metodo realiza o calculo da matratriz escalonada pelo metodo de gauss 
@param mArray is a a multidimensional array data represents the matrix
that you want to the scalonate usin gauss methoed
'''
def calcMatriz(mArray):
    print(mArray)
    return mArrat

In [4]:
listMatrix=[]
listLinha=[]
print("Digite o tamanho da matriz")
n=int(input())
for linha in range(0, n):
    for coluna in range(0, n+1):
        print(f"Digite o elemento presente na linha {linha} coluna {coluna}: ")
        listLinha.append(int(input()))
    listMatrix.append(listLinha)
    listLinha=[]
calcMatriz(np.array(listMatrix))
    

Digite o tamanho da matriz
3
Digite o elemento presente na linha 0 coluna 0: 
1
Digite o elemento presente na linha 0 coluna 1: 
2
Digite o elemento presente na linha 0 coluna 2: 
3
Digite o elemento presente na linha 0 coluna 3: 
4
Digite o elemento presente na linha 1 coluna 0: 
1
Digite o elemento presente na linha 1 coluna 1: 
2
Digite o elemento presente na linha 1 coluna 2: 
3
Digite o elemento presente na linha 1 coluna 3: 
4
Digite o elemento presente na linha 2 coluna 0: 
1
Digite o elemento presente na linha 2 coluna 1: 
2
Digite o elemento presente na linha 2 coluna 2: 
3
Digite o elemento presente na linha 2 coluna 3: 
4
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


NameError: name 'eArrat' is not defined